return {
  { name = 'add-dir', desc = 'Add additional working directories' },
  { name = 'agents', desc = 'Manage custom AI subagents' },
  { name = 'bashes', desc = 'List background tasks' },
  { name = 'bug', desc = 'Report bugs to Anthropic' },
  { name = 'clear', desc = 'Clear conversation history' },
  { name = 'compact', desc = 'Compact conversation' },
  { name = 'config', desc = 'Open Settings' },
  { name = 'context', desc = 'Visualize context usage' },
  { name = 'cost', desc = 'Show token usage' },
  { name = 'doctor', desc = 'Check installation health' },
  { name = 'exit', desc = 'Exit the REPL' },
  { name = 'export', desc = 'Export conversation' },
  { name = 'help', desc = 'Get usage help' },
  { name = 'hooks', desc = 'Manage hooks' },
  { name = 'ide', desc = 'Manage IDE integrations' },
  { name = 'init', desc = 'Initialize CLAUDE.md' },
  { name = 'install-github-app', desc = 'Setup GitHub Actions' },
  { name = 'login', desc = 'Switch accounts' },
  { name = 'logout', desc = 'Sign out' },
  { name = 'mcp', desc = 'Manage MCP servers' },
  { name = 'memory', desc = 'Edit CLAUDE.md' },
  { name = 'model', desc = 'Select AI model' },
  { name = 'output-style', desc = 'Set output style' },
  { name = 'permissions', desc = 'View permissions' },
  { name = 'plan', desc = 'Enter plan mode' },
  { name = 'plugin', desc = 'Manage plugins' },
  { name = 'pr-comments', desc = 'View PR comments' },
  { name = 'privacy-settings', desc = 'Privacy settings' },
  { name = 'release-notes', desc = 'View release notes' },
  { name = 'rename', desc = 'Rename session' },
  { name = 'remote-env', desc = 'Configure remote env' },
  { name = 'resume', desc = 'Resume conversation' },
  { name = 'review', desc = 'Request code review' },
  { name = 'rewind', desc = 'Rewind conversation' },
  { name = 'sandbox', desc = 'Enable sandbox' },
  { name = 'security-review', desc = 'Security review' },
  { name = 'stats', desc = 'Visualize usage' },
  { name = 'status', desc = 'Show status' },
  { name = 'statusline', desc = 'Setup statusline' },
  { name = 'teleport', desc = 'Resume remote session' },
  { name = 'terminal-setup', desc = 'Install keybindings' },
  { name = 'theme', desc = 'Change theme' },
  { name = 'todos', desc = 'List TODOs' },
  { name = 'usage', desc = 'Show usage limits' },
  { name = 'vim', desc = 'Enter vim mode' },
}
